### ISSUE TITLE
Add instructions on how to cite "grainyhead"

### ISSUE THREAD

**Issue by matentzn** [gouttegd/grainyhead#19]
In the absence of any other instructions, I will simply add a link to the repo to the papers I am writing)

**Comment by gouttegd** [comment]
Why would you even want to cite Grainyhead? o_O It’s a tool to gather stats on GitHub repos and close old issues, not any kind of scientific tool.

I can put it on Zenodo if you want, but citing a mere tool like Grainyhead seems overkill to me. At this rate, why not also cite Git, your favourite code editor, your web browser… they are all tools that help you do your job.

**Comment by matentzn** [comment]
I am a big fan of attribution. You are not? You cannot imagine how much time and effort your tool has saved me already.. we are talking many dozens of hours. So why not say it!

**Comment by gouttegd** [comment]
But what about all the other tools you use without even thinking about it? How many times have you used `grep` to find a pattern in a file? I am willing to bet that over the years, `grep` saved you a whole lot more time than Grainyhead! So why not cite [Mike Haertel et al.](https://git.savannah.gnu.org/cgit/grep.git/tree/AUTHORS)?

Anyway, I activated Zenodo on the Grainyhead repository, so it will get a citable DOI upon the next release. But I will _not_ create a release now (while there has been no changes since the last one) just to get a DOI!

In the meantime, I suggest an attribution in the form of a blurb like the following in the “acknowledgements“ section of your papers:

> This work was made possible by the contributions of countless of free software developers, upon which much of our modern infrastructure is built.

**Comment by matentzn** [comment]
Haha great. I Love This acknowledgement, I will try to sneak it in.

**Comment by gouttegd** [comment]
If you really want to cite something, you can also try “Munroe, Randall (2020). _Dependency_. https://xkcd.com/2347/”. 😛

**Comment by gouttegd** [comment]
⬆️ This is not (really) a joke. Well, OK, it is, but I do think that someone should do that one day, if it has not been done already.

**Comment by gouttegd** [comment]
I forgot that you don’t necessarily need a new release to archive an artifact on Zenodo (it’s only necessary for the _automated_ archiving process, but you can always archive an artifact manually), so it’s done.

(That shouldn’t dispense you from acknowledging the implicit contributions of free software developers as a whole, though.)

**Comment by matentzn** [comment]
I just added it to a major paper I am writing. Lets see if it remains.

**Comment by gouttegd** [comment]
If it gets removed, I’d be curious to hear the complaint(s) about it and the reason(s) for the removal.

**Comment by matentzn** [comment]
I will let you know when the arguments against trickle in: 
<img width="1161" alt="image" src="https://github.com/gouttegd/grainyhead/assets/7070631/f9ad4b00-01a9-416c-9bad-a5afaa8ee011">
