### ISSUE TITLE
Feature request: serialise results as JSON

### ISSUE THREAD

**Issue by matentzn** [gouttegd/grainyhead#8]
ATM, grainyhead generates these nice markdown tables:

| Event                | Total | Internal | External | Ext. (%) |
| -------------------- | ----- | -------- | -------- | -------- |
| Issues opened        |   707 |      302 |      405 |    57.28 |
| Issues closed        |   811 |      777 |       34 |     4.19 |
| Pull requests opened |  1023 |      829 |      194 |    18.96 |
| Pull requests closed |   977 |      937 |       40 |     4.09 |
| Pull requests merged |   897 |      869 |       28 |     3.12 |
| Comments             |  2340 |     1665 |      675 |    28.85 |
| Commits              |  3208 |     2850 |      358 |    11.16 |
| Contributors         |    86 |       13 |       73 |    84.88 |
| Releases             |    14 |          |          |          |

To use it in our web app, we need that same output to be generated as a JSON file. Maybe `-o output.json`?

**Comment by gouttegd** [comment]
Any idea/constraints on what the JSON should look like?

Would something like the following be okay?
```json
{
	"Repository": "obophenotype/uberon",
	"Period": {
		"From": "2020-01-01",
		"To": "2020-12-31"
		},
	"Contributors": {
		"Total": 48,
		"Members": 35
	},
	"Contributions": {
		"All": {
			"Issues": {
				"Opened": 486,
				"Closed": 236
			},
			"Pull requests": {
				"Opened": 123,
				"Closed": 64,
				"Merged": 54
			},
			"Comments": 456,
			"Commits": 789,
			"Releases": 5
		},
		"Team":	{
			"Name": "uberon-cl-curators",
			"Issues": {
				"Opened": 345,
				"Closed": 234
				},
			"Pull requests": {
				"Opened": 27,
				"Closed": 18,
				"Merged": 15
			},
			"Comments": 345,
			"Commits": 678,
			"Releases": 5
		},
		"Individuals": [
			{
				"Handle": "gouttegd",
				"Issues": {
					"Opened": 5,
					"Closed": 4
					},
				"Pull requests": {
					"Opened": 8,
					"Closed": 5,
					"Merged": 4
				},
				"Comments": 68,
				"Commits": 52,
				"Releases": 0
			},
			{
				"Handle": "matentzn",
				"Issues": {
					"Opened": 5,
					"Closed": 4
					},
				"Pull requests": {
					"Opened": 8,
					"Closed": 5,
					"Merged": 4
				},
				"Comments": 68,
				"Commits": 52,
				"Releases": 0
			}
		]
	}
}
```

**Comment by gouttegd** [comment]
The above sample would imply that the consumer code has to compute the “internal”/“external” ratios itself. Otherwise I can add another dictionary “Contribution ratios” (or similar):

```json
    …
    "External contribution ratios": {
        "Issues": {
            "Opened": 0.65
            "Closed": 0.27
        },
        etc
    }
    …
```

**Comment by matentzn** [comment]
This is awesome! I would personally recommend to 

- keep all elements in this schema lower case
- explicitly add the external sections under the `team` section
- I would probably not add the ratios and leave that up to the client, but up to you..

**Comment by gouttegd** [comment]
Implemented in 7b44ff1. Call the command with `--json`:

```sh
$ grh -s uberon metrics --from 2020-01-01 --to 2021-12-31 --team uberon-cl-curators --json
{
  "period": {
    "to": "2020-01-01",
    "from": "2021-12-31"
  },
  "contributors": {
    "total": 79,
    "internal": 22,
    "external": 57
  },
  "contributions": {
    "all": {
      "issues": {
        "opened": 420,
        "closed": 660
      },
      "pull requests": {
        "opened": 332,
        "closed": 272,
        "merged": 204
[...]
```

Use a standard shell redirection to write to a file for later consumption.

**Comment by matentzn** [comment]
```
grh -s mondo metrics --from=2020-06-30 --to=2020-08-25 --team monarch-ontology-team --json > mondo.json
```

JSON output:

```
{
  "period": {
    "to": "2020-06-30",
    "from": "2020-08-25"
  },
  "contributors": {
    "total": 27,
    "internal": 7,
    "external": 20
  },
  "contributions": {
    "all": {
      "issues": {
        "opened": 62,
        "closed": 99
      },
      "pull requests": {
        "opened": 120,
        "closed": 141,
        "merged": 118
      },
      "comments": 312,
      "commits": 325,
      "releases": 3
    },
    "internal": {
      "issues": {
        "opened": 33,
        "closed": 98
      },
      "pull requests": {
        "opened": 120,
        "closed": 141,
        "merged": 118
      },
      "comments": 235,
      "commits": 325
    },
    "external": {
      "issues": {
        "opened": 29,
        "closed": 1
      },
      "pull requests": {
        "opened": 0,
        "closed": 0,
        "merged": 0
      },
      "comments": 77,
      "commits": 0
    },
    "individuals": [
      {
        "handle": "balhoff",
        "issues": {
          "opened": 0,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 1,
        "commits": 0
      },
      {
        "handle": "pnrobinson",
        "issues": {
          "opened": 5,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 10,
        "commits": 0
      },
      {
        "handle": "mayherpatel",
        "issues": {
          "opened": 1,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 1,
        "commits": 0
      },
      {
        "handle": "tibingaman",
        "issues": {
          "opened": 2,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 9,
        "commits": 0
      },
      {
        "handle": "RedRiver1816",
        "issues": {
          "opened": 1,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 0,
        "commits": 0
      },
      {
        "handle": "maglott",
        "issues": {
          "opened": 9,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 13,
        "commits": 0
      },
      {
        "handle": "brookepalus",
        "issues": {
          "opened": 1,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 2,
        "commits": 0
      },
      {
        "handle": "paolaroncaglia",
        "issues": {
          "opened": 2,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 5,
        "commits": 0
      },
      {
        "handle": "saramsey",
        "issues": {
          "opened": 1,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 1,
        "commits": 0
      },
      {
        "handle": "TomConlin",
        "issues": {
          "opened": 0,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 1,
        "commits": 0
      },
      {
        "handle": "kshefchek",
        "issues": {
          "opened": 0,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 2,
        "commits": 0
      },
      {
        "handle": "drseb",
        "issues": {
          "opened": 0,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 1,
        "commits": 0
      },
      {
        "handle": "nicolevasilevsky",
        "issues": {
          "opened": 22,
          "closed": 80
        },
        "pull requests": {
          "opened": 112,
          "closed": 111,
          "merged": 89
        },
        "comments": 191,
        "commits": 273
      },
      {
        "handle": "ahamosh",
        "issues": {
          "opened": 0,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 6,
        "commits": 0
      },
      {
        "handle": "ValWood",
        "issues": {
          "opened": 1,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 7,
        "commits": 0
      },
      {
        "handle": "ErinRiggs",
        "issues": {
          "opened": 0,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 2,
        "commits": 0
      },
      {
        "handle": "asmvernon",
        "issues": {
          "opened": 0,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 1,
        "commits": 0
      },
      {
        "handle": "lcdaugherty",
        "issues": {
          "opened": 4,
          "closed": 1
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 3,
        "commits": 0
      },
      {
        "handle": "JadeHotchkiss",
        "issues": {
          "opened": 0,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 3,
        "commits": 0
      },
      {
        "handle": "tsneddon",
        "issues": {
          "opened": 4,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 1,
        "commits": 0
      },
      {
        "handle": "cmungall",
        "issues": {
          "opened": 5,
          "closed": 18
        },
        "pull requests": {
          "opened": 5,
          "closed": 30,
          "merged": 29
        },
        "comments": 25,
        "commits": 47
      },
      {
        "handle": "matentzn",
        "issues": {
          "opened": 1,
          "closed": 0
        },
        "pull requests": {
          "opened": 3,
          "closed": 0,
          "merged": 0
        },
        "comments": 5,
        "commits": 5
      },
      {
        "handle": "Antonialock",
        "issues": {
          "opened": 0,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 2,
        "commits": 0
      },
      {
        "handle": "colleenXu",
        "issues": {
          "opened": 1,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 1,
        "commits": 0
      },
      {
        "handle": "Khuthalamnika",
        "issues": {
          "opened": 0,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 2,
        "commits": 0
      },
      {
        "handle": "abbe-Lai",
        "issues": {
          "opened": 2,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 1,
        "commits": 0
      },
      {
        "handle": "galyea-gard",
        "issues": {
          "opened": 0,
          "closed": 0
        },
        "pull requests": {
          "opened": 0,
          "closed": 0,
          "merged": 0
        },
        "comments": 16,
        "commits": 0
      }
    ]
  }
}
```

**Comment by cmungall** [comment]
looks great.

some may prefer keys in dicts to have no spaces, but I'm OK with it.

**Comment by cmungall** [comment]
I know @matentzn said no feature requests, but if we are deciding on a standard we have to think how this will work for extensions. E.g. if we want stats broken down by github labels

**Comment by gouttegd** [comment]
Random thoughts:

* We can settle on a core `contribution` dictionary schema to store all metrics independently of how they have been collected. That can be very similar to what we currently have:

```json
{
    "issues": {
        "opened": 99,
        "closed": 88
    },
    "pull_requests": {
        "opened": 77,
        "closed": 66,
        "merged": 55
    },
    "comments": 44,
    "commits": 33,
    "releases": 22
}
```

* The `contributions` dictionary member can then be an array as follows:

```json
{
    "contributions": [
        {
            "selector": "<a selector expression>",
            "results": <a contribution object as illustrated above>
        },
        {
            "selector": "<another selector>",
            "results": <another contribution object>
        }
    ]
}
```

* “Selector expressions” could be:
  * `all`: no filtering, compute metrics on the entire repo for the period,
  * `team:X`: compute metrics on items or events originating from members of team _X_,
  * `user:Y`: compute metrics on items or events originating from user _Y_,
  * `label:Z`: compute metrics on items carrying the label _Z_ or events associated with items carrying the label _Z_,
  * `-selector`: compute metrics on items or events not selected by _selector_ (e.g. `-team:X` selects items or events _not_ originating from members of team _X_).
  * More selectors could be added later.

* On the command line, add a `--filters` option to specify the filter(s) to use.
  * Default would be `all`, giving only the metrics from the entire repo without filtering.
  * `--filters all,team:X,-team:X` would produce three `contribution` objects, for the full metrics, the metrics for team _X_, and the metrics for the rest of the world, respectively.
  * `user:*` would be a shortcut for `user:user1,user:user2,user:user3…`. That is, it would produce an array of `contribution` objects, one for each known contributor.
  * Likewise, `label:*` would be a shortcut to break down the metrics across all existing labels in the repository.
  * `config:X` would mean “the filter saved under the name _X_ in the configuration file” (how would filters be stored in the configuration file will need more random thoughts).

Would there be an interest in allowing to combine filters? That is, e.g., compute the metrics on items or events originating from a given team _and_ carrying a given label? If so, that would require further thoughts, because the syntax to specify such filters could quickly become complicated.

**Comment by matentzn** [comment]
- I also prefer no spaces in json keys, better use underscore/lowercase alphanumeric ascii everywhere for keys
- @gouttegd I like your suggestion! That is great. One question. Lets say we permit nested groups (not now, lets just say we want that in the future), term (external/internal), tag (new term request, other). How would you represent this? like:

```
--selector "team:x|label:bug"
```

And leave it up to the client to display it correctly? I think its fine, just checking whether this would complicate things..

**Comment by gouttegd** [comment]
> How would you represent this? 

Excellent question, and that’s exactly what will require further thoughts.

If we allow to combine filters, then it means that we need a way to express 3 different things:

* The use of different filters to produce different results (without combining the filters). For example, `label:X, label:Y`, which, as per the rules above, would produce a first set of results for the items and events with label _X_, then a second (independent) set of results for items and events with label _Y_.
* The intersection (“logical AND“) of two filters. For example, `label:X & label:Y` would produce a single set of results for items and events marked with both labels _X_ and _Y_.
* The union (“logical OR“) of two filters. For example, `label:X | label:Y` would produce a single set of results for items and events marked with label _X_ or label _Y_.

Then we could also probably support parentheses or a similar way of grouping filters together, so that we can say, e.g.

* `team:T & (label:X | label:Y)`: one set of results, for items carrying labels _X_ or _Y_ and originating from team _T_
* `team:T & !(label:X | label:Y)`: one set of results, for items carrying neither label _X_ or label _Y_ and originating from team _T_ (using `!` as the negation marker instead of `-` as in the previous message)
* `(team:T, -team:T) & label:X`: two sets of results, one for items originating from team _T_ and one for items originating from outside team _T_, in both cases only items carrying the _X_ label (would be a shortcut for `team:T & label:X, -team:T & label:X`)

All of that to say that we can do a lot of complicated things. I don’t mind that, but I’d like to plan things carefully for once.

**Comment by gouttegd** [comment]
Ah, and of course, we should probably support a syntax to allow the user to specify its own filtering code (as a Python module to be downloaded from the Internet, as in `custom:http://example.org/filter.py`), so that we can have our own critical code injection vulnerability even if we don’t use Log4J! 😛

**Comment by matentzn** [comment]
YOU ARE CRAZY!

**Comment by matentzn** [comment]
I think this is too complex, but up to you. The important thing is that the simple case stays simple, i.e:

```
{
    "contributions": [
        {
            "selector": "team:A",
            "results": <a contribution object as illustrated above>
        },
        {
            "selector": "label:QC",
            "results": <another contribution object>
        }
    ]
}
```

As long as that generally works, I think we are good - we do however need somehow to describe the opposite, i.e. NOT team:X (to denote external). Maybe `!team:X`? I don't think we have to generate results for the complement automagically. If the client says: --select team:x, the can ask for --select !team:x.

**Comment by matentzn** [comment]
But your language is sort of awesome :D

**Comment by gouttegd** [comment]
> we do however need somehow to describe the opposite, i.e. NOT team:X (to denote external). Maybe `!team:X`?

Yes, that’s what I had in mind.

> I don't think we have to generate results for the complement automagically. If the client says: --select team:x, the can ask for --select !team:x

Good. I was not planning to automatically create complementary sets. Only give the user what they explicitly requested.

The only exception (kind of) would be the `user:*` syntax, which would automatically create result sets for _all_ contributors. This syntactic sugar is justified because it dispenses the user from having to know beforehand who the contributors are (so that they don’t need to write `user:gouttegd,user:matentzn,user:cmungall,…` and so on for dozens of contributors). Same for `label:*`.

**Comment by matentzn** [comment]
And I think your AND OR grammar also makes sense. let's not add whitespace at all, and we are good to go.

**Comment by gouttegd** [comment]
Another question is, for cases where the user asks for more than one result sets, how do we establish the link between each result set and the corresponding filter.

That is, if the user asks for, say `team:X, !team:X`, then we give them two result sets. How will they know which result set is for `team:X` and which is for `!team:X`?

I am no longer sure the approach as in the example below is a good idea:

```
{
    "contributions": [
        {
            "selector": "team:X",
            "results": <a contribution object>
        },

        {
            "selector": "!team:X",
            "results": <a contribution object>
        },
```

The problem of that approach is that it ties the result format to the command-line filter syntax, and I don’t think it is a good idea.

I have no better idea for now. More random thoughts needed.

**Comment by matentzn** [comment]
Why cant we have the client worrying about that link?

**Comment by matentzn** [comment]
Better than adding more nesting in the json i would think..

**Comment by gouttegd** [comment]
> Why cant we have the client worrying about that link?

Fine with me. From my point of view, for now the client is you. Happy to let _you_ worry about that! :p

**Comment by matentzn** [comment]
I like it :) I am not worried about the exact form, and a list with a clear schema where I only have to worry about the interpretation of the selector string sounds great

**Comment by gouttegd** [comment]
In addition to the selector string, I think I can also guarantee that the result sets will be in the same order as in the filter string on the command line. So if you ask for `all, team:X, !team:X`, even without looking at the selector strings you can expect to have, in the `contributions` array, first the “overall” metrics, then the metrics for team _X_, then the metrics for the rest of the world.

**Comment by matentzn** [comment]
Perfect!

**Comment by matentzn** [comment]
@gouttegd we are ready to start building our dashboard now, just a kind prod in case you find some time to deliver this piece :P Sorry my friend.

**Comment by gouttegd** [comment]
This _will_ be delivered… at some point. But this is _far_ away on my radar at the moment, sorry.

**Comment by matentzn** [comment]
fair enough :) Thanks!

**Comment by gouttegd** [comment]
@matentzn Work on this feature is in progress, though again I make no promise as to when it will be available.

Here is an example of a `metrics` run where, in addition to the “standard“ internal-vs-external stats, we also get stats for issues and pull requests labelled with `new term request` (NTR):

| Event                | Total    | Internal | Int. (%) | External | Ext. (%) | NTR      | NTR  (%) |
| -------------------- | -------- | -------- | -------- | -------- | -------- | -------- | -------- |
| Contributors         |       47 |       20 |    42.55 |       27 |    57.45 |       12 |    25.53 |
| Issues opened        |      190 |      120 |    63.16 |       70 |    36.84 |       50 |    26.32 |
| Issues closed        |      138 |      137 |    99.28 |        1 |     0.72 |       28 |    20.29 |
| Pull requests opened |      203 |      196 |    96.55 |        7 |     3.45 |        4 |     1.97 |
| Pull requests closed |      167 |      167 |   100.00 |        0 |     0.00 |        2 |     1.20 |
| Pull requests merged |      142 |      142 |   100.00 |        0 |     0.00 |        1 |     0.70 |
| Comments             |     1116 |      968 |    86.74 |      148 |    13.26 |        0 |     0.00 |
| Commits              |      502 |      492 |    98.01 |       10 |     1.99 |        0 |     0.00 |
| Releases             |        5 |        5 |   100.00 |        0 |     0.00 |        0 |     0.00 |

indicating, for example, that in the past 6 months ~26% (50 out of 190) issues opened in Uberon were new term requests.

Here is the corresponding JSON:

```
{
  "period": {
    "to": "2022-05-02",
    "from": "2021-11-03"
  },
  "contributions": [
    {
      "selector": "all",
      "results": {
        "contributors": 47,
        "issues": {
          "opened": 190,
          "closed": 138
        },
        "pull_requests": {
          "opened": 203,
          "closed": 167,
          "merged": 142
        },
        "comments": 1116,
        "commits": 502,
        "releases": 5
      }
    },
    {
      "selector": "team:uberon-cl-curators",
      "results": {
        "contributors": 20,
        "issues": {
          "opened": 120,
          "closed": 137
        },
        "pull_requests": {
          "opened": 196,
          "closed": 167,
          "merged": 142
        },
        "comments": 968,
        "commits": 492,
        "releases": 5
      }
    },
    {
      "selector": "!team:uberon-cl-curators",
      "results": {
        "contributors": 27,
        "issues": {
          "opened": 70,
          "closed": 1
        },
        "pull_requests": {
          "opened": 7,
          "closed": 0,
          "merged": 0
        },
        "comments": 148,
        "commits": 10,
        "releases": 0
      }
    },
    {
      "selector": "label:new term request",
      "results": {
        "contributors": 12,
        "issues": {
          "opened": 50,
          "closed": 28
        },
        "pull_requests": {
          "opened": 4,
          "closed": 2,
          "merged": 1
        },
        "comments": 0,
        "commits": 0,
        "releases": 0
      }
    }
  ]
}
```

**Comment by matentzn** [comment]
I think this looks awesome. THANKS for working on this!

**Comment by gouttegd** [comment]
A preview is available in the [custom-metrics](https://github.com/gouttegd/grainyhead/tree/custom-metrics) branch.

The `metrics` command now accepts as many `--selector` option as needed. Each `selector` option instructs GRH to generate metrics for a subset of the repository. For now, possible selector values are:

* `all`: generate metrics for the entire repository;
* `team:X`: generate metrics for events caused by members of team `X`;
* `label:Y`: generate metrics for issues/pull requests tagged with label `Y`
* `!ZZZ`: selects the opposite of selector `ZZZ` (e.g., `!team:X` generate metrics for events caused by users that do _not_ belong to team `X`; `!label:Y` generate metrics for issues/pull requests _not_ tagged with label `Y`).

Example:

```
$ grh metrics --selector all --selector team:uberon-cl-curators --selector '!team:uberon-cl-curators' --selector label:tech --json
```

would generate 4 sets of results: one for all events, one for events from the _uberon-cl-curators_ team, one for the complementary set of events _not_ from that team, and one for events tagged with `Tech`.

Not implemented yet:

* the `user:` selector;
* the `&` and `|` operators, to allow to combine selectors (e.g. `team:uberon-cl-curators & label:new term request`);
* wildcards (e.g., `--selector 'label:*'` as a syntactic sugar for `--selector label:label1 --selector label:label2 --selector label:label3`... and so on for all labels in the repo);
* the parenthesis operator (e.g., `team:T & (label:X | label:Y)`).

The `user:` selector and the `&` and `|` operators shouldn’t be difficult to add (I know… famous last words) and will be next. Wildcards and parentheses are not a priority for now.

**Comment by gouttegd** [comment]
Also not implemented: any kind of error checking, so an incorrectly specified selector might yield “interesting” results, ranging from an uncaught exception to a cataclysmic space-time paradox.

**Comment by matentzn** [comment]
Given the state of the world, a mere cataclysmic space time event would be a welcome distraction, so please avoid all too rigorous error checking.

**Comment by gouttegd** [comment]
Actually I’ve merged the new code to `master`. Not everything is done, but what is done is working fine, so there’s no need to confine that to a branch.

Feel free to update your local installation and start testing the `--selector` option.

(If you do not specify any `--selector`, then the previous behaviour applies and `grh` will generate a report for the entire repo, for the “internal” contributors, and for the “external contributors”. That is,

```
$ grh metrics --team uberon-cl-curators
```

is equivalent to

```
$ grh metrics --selector all --selector team:uberon-cl-curators --selector '!team:uberon-cl-curators'
```

)

**Comment by matentzn** [comment]
Thank you, I will let my teams know to test the feature :)

**Comment by gouttegd** [comment]
Latest developments:

* CSV/TSV output: JSON is fine for consumption by custom code, but if someone wants to play with the stats in a standard spreadsheet program, a standard CSV or TSV output can be nice.

So the `--json` option of `metrics` is now replaced by a `--format` option, which accepts one of `markdown` (default), `json` (produces the kind of output discussed in this thread), `csv`, and `tsv`.

Sample CSV output:

```
$ % grh metrics --format csv --team uberon-cl-curators
Date,Selector,Selector name,Issues opened,Issues closed,Pull requests opened,Pull requests closed,Pull requests merged,Comments,Commits,Releases,Contributors
2022-05-03,all,Total,234,164,253,179,152,1124,638,6,45
2022-05-03,team:uberon-cl-curators,Internal,163,163,252,179,152,989,634,6,20
2022-05-03,!team:uberon-cl-curators,External,71,1,1,0,0,135,4,0,25
```

The first column (`Date`) is the end of the selected reporting period (value of the `--to` option, here left to the default value of `today`).

Column 2 (`Selector`) is the selector string; column 3 is a human-readable variant of the selector string, if available.

The other columns contain the stats proper.


* Periodic reports: Because it can be nice to have stats broken down by periods, the command now accepts a `--period` option, which can take the following values: `weekly`, `monthly`, `quarterly`, and `yearly`. When that option is used, the full reporting period (as specified by `--from` and `--to`) is broken down in weekly/monthly/quarterly/yearly intervals.

Example:

```
$ grh metrics --selector "all AS Total" --from 2021-01-01 --to 2021-12-31 --period monthly --format csv 
Date,Selector,Selector name,Issues opened,Issues closed,Pull requests opened,Pull requests closed,Pull requests merged,Comments,Commits,Releases,Contributors
2021-01-31,all,Total,68,20,42,20,16,87,46,0,15
2021-02-28,all,Total,28,28,34,64,34,81,137,2,11
2021-03-31,all,Total,40,12,16,10,10,61,36,0,16
2021-04-30,all,Total,36,2,0,6,4,46,6,0,17
2021-05-31,all,Total,66,40,22,18,18,81,46,0,13
2021-06-30,all,Total,42,48,52,42,38,125,116,0,17
2021-07-31,all,Total,62,70,80,82,48,207,169,6,16
2021-08-31,all,Total,34,860,24,28,20,567,65,2,20
2021-09-30,all,Total,28,28,32,30,20,97,80,0,15
2021-10-31,all,Total,64,54,94,68,60,224,165,2,18
2021-11-30,all,Total,87,61,93,63,55,151,278,4,17
2021-12-31,all,Total,16,15,16,8,8,110,32,0,16
2022-01-31,all,Total,12,22,24,23,21,250,96,0,21
```

**Comment by matentzn** [comment]
Wow, cool!

**Comment by gouttegd** [comment]
The `user:` selector and the use of wildcards (`user:*` for stats for all users and `label:*` for stats for all labels) have been implemented.

Closing here, as this issue is no longer about “JSON serialisation”.

For discussion about the feature of selector combinations, see the new ticket #10.
